// <auto-generated />
namespace spreaders.lib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ForignKeyFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForignKeyFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201701071718055_ForignKeyFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
