spreaders.pages.transaction=function(){var b=function(a,b,c,d,f){var e=this;this.pageContext=a;this.urlService=b;this.storage=c;this.observer=d;this.synchroniser=f;this.isPayerRadiosRendered=this.isPayeeCheckboxesRendered=!1;this.currentGroup;this.populateBackButton();this.storage.getGroup(this.pageContext.getCurrentGroupId()).then(function(a){e.populateForm(a)});this.observer.subscribe("payeeCheckboxesRendered",this.payeeCheckboxesRendered,this);this.observer.subscribe("payerRadiosRendered",this.payerRadiosRendered,
this);this.synchroniser.startServiceWorker()};b.prototype.populateBackButton=function(){document.getElementsByClassName("backButton")[0].href=this.urlService.getTransactionsPage(this.pageContext.getCurrentGroupId())};b.prototype.populateForm=function(a){this.currentGroup=a;this.radiosContainer=document.getElementsByClassName("payerRadios")[0];this.payerRadios=new spreaders.view.payerRadio(this.currentGroup,this.radiosContainer,this.storage,this.observer);this.checkboxsContainer=document.getElementsByClassName("payeeCheckboxs")[0];
this.payeeCheckboxes=new spreaders.view.payeeCheckboxes(this.currentGroup,this.checkboxsContainer,this.storage,this.observer);this.amountInput=document.getElementsByName("amount")[0];this.amountInputError=document.getElementsByClassName("error_amount")[0];this.descriptionInput=document.getElementsByName("description")[0];this.submitButton=document.getElementsByClassName("submit")[0];this.addSubmitEvent()};b.prototype.payeeCheckboxesRendered=function(){this.isPayeeCheckboxesRendered=!0;this.addTransactionBeingEdited()};
b.prototype.payerRadiosRendered=function(){this.isPayerRadiosRendered=!0;this.addTransactionBeingEdited()};b.prototype.addTransactionBeingEdited=function(){var a=this;this.isPayeeCheckboxesRendered&&this.isPayerRadiosRendered&&(this.transactionBeingEditedId=this.pageContext.getCurrentTransaction(),this.isGuid(this.transactionBeingEditedId)&&this.storage.getTransaction(this.transactionBeingEditedId).then(function(b){a.addTransactionBeingEditedCallback(b)}))};b.prototype.addTransactionBeingEditedCallback=
function(a){this.transactionBeingEdited=a;this.payerRadios.addSelectedValue(this.transactionBeingEdited.payer);this.payeeCheckboxes.addSelectedValues(this.transactionBeingEdited.payees);this.amountInput.value=this.transactionBeingEdited.amount;this.descriptionInput.value=this.transactionBeingEdited.description;this.submitButton.innerHTML="update"};b.prototype.addSubmitEvent=function(){this.submitButton.addEventListener("click",this.processSubmit.bind(this))};b.prototype.processSubmit=function(a){a.preventDefault();
this.hideAllErrors();this.formIsValid()?this.saveTransactionAndRedirect():this.displayErrors()};b.prototype.hideAllErrors=function(){errorElements=document.getElementsByClassName("error");for(var a=0;a<errorElements.length;a++)errorElements[a].style.display="none"};b.prototype.formIsValid=function(){return this.payerRadios.isValid()&&this.payeeCheckboxes.isValid()&&""!==this.amountInput.value};b.prototype.saveTransactionAndRedirect=function(){var a=this.payerRadios.getValues()[0],b=this.payeeCheckboxes.getValues(),
c=parseFloat(this.amountInput.value).toFixed(2),d=this.descriptionInput.value;this.isGuid(this.transactionBeingEditedId)?(this.transactionBeingEdited.payer=a,this.transactionBeingEdited.payees=b,this.transactionBeingEdited.amount=c,this.transactionBeingEdited.description=d,this.transactionBeingEdited.updatedOn=this.storage.getUtcUnixTimeStamp(),this.storage.updateTransaction(this.transactionBeingEdited,!0)):(a=new spreaders.model.transaction(this.currentGroup,a,b,c,d),a.createdOn=this.storage.getUtcUnixTimeStamp(),
a.updatedOn=this.storage.getUtcUnixTimeStamp(),this.storage.addTransaction(a));this.synchroniser.syncWithServer();window.location.href=this.urlService.getTransactionsPage(this.pageContext.getCurrentGroupId())};b.prototype.displayErrors=function(){this.payerRadios.displayError();this.payeeCheckboxes.displayError();this.amountInput.value||(this.amountInputError.style.display="block")};b.prototype.isGuid=function(a){return/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.test(a)};
return b}();var storage=new spreaders.storage;storage.connect().then(function(b){b=new spreaders.urlService;var a=new spreaders.pageContext(b),e=new spreaders.observer,c=new spreaders.apiService;c=new spreaders.sync.synchroniser(storage,c);new spreaders.pages.transaction(a,b,storage,e,c)});
