var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(b){return b instanceof e?b:new e(function(a,c){a(b)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(b){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(b);return this};b.prototype.asyncExecuteBatch_=function(){var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(b){d(b,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=this.batch_;this.batch_=[];for(var a=0;a<b.length;++a){var c=b[a];delete b[a];try{c()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var e=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{b(a.resolve,a.reject)}catch(h){a.reject(h)}};e.prototype.createResolveAndReject_=
function(){function b(b){return function(d){c||(c=!0,b.call(a,d))}}var a=this,c=!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};e.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof e)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};e.prototype.resolveToNonPromiseObj_=function(b){var a=
void 0;try{a=b.then}catch(h){this.reject_(h);return}"function"==typeof a?this.settleSameAsThenable_(a,b):this.fulfill_(b)};e.prototype.reject_=function(b){this.settle_(2,b)};e.prototype.fulfill_=function(b){this.settle_(1,b)};e.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a|"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=
this.onSettledCallbacks_,a=0;a<b.length;++a)b[a].call(),b[a]=null;this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(b){var a=this.createResolveAndReject_();b.callWhenSettled_(a.resolve,a.reject)};e.prototype.settleSameAsThenable_=function(b,a){var c=this.createResolveAndReject_();try{b.call(a,c.resolve,c.reject)}catch(k){c.reject(k)}};e.prototype.then=function(b,a){function c(b,a){return"function"==typeof b?function(a){try{d(b(a))}catch(l){g(l)}}:a}var d,g,f=new e(function(b,
a){d=b;g=a});this.callWhenSettled_(c(b,d),c(a,g));return f};e.prototype.catch=function(b){return this.then(void 0,b)};e.prototype.callWhenSettled_=function(b,a){function c(){switch(d.state_){case 1:b(d.result_);break;case 2:a(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(function(){f.asyncExecute(c)})};e.resolve=c;e.reject=function(b){return new e(function(a,c){c(b)})};e.race=function(b){return new e(function(a,
d){for(var e=$jscomp.makeIterator(b),f=e.next();!f.done;f=e.next())c(f.value).callWhenSettled_(a,d)})};e.all=function(b){var a=$jscomp.makeIterator(b),d=a.next();return d.done?c([]):new e(function(b,e){function f(a){return function(c){g[a]=c;h--;0==h&&b(g)}}var g=[],h=0;do g.push(void 0),h++,c(d.value).callWhenSettled_(f(g.length-1),e),d=a.next();while(!d.done)})};return e},"es6","es3");
$jscomp.polyfill("Object.is",function(a){return a?a:function(b,a){return b===a?0!==b||1/b===1/a:b!==b&&a!==a}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(b,a){var c=this;c instanceof String&&(c=String(c));var e=c.length;for(a=a||0;a<e;a++)if(c[a]==b||Object.is(c[a],b))return!0;return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(b,a){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,a||0)}},"es6","es3");
spreaders.pages.transactions=function(){var a=function(b,a,d,e,f,g){this.group;this.pageContext=b;this.urlService=a;this.apiService=d;this.storage=e;this.observer=f;this.synchroniser=g;this.people=[];this.transactions=[];this.addSection=document.getElementsByClassName("addSection")[0];this.opaqueLayer=document.getElementsByClassName("opaqueLayer")[0];this.personTotalsContainer=document.getElementsByClassName("personTotals")[0];this.transactionContainer=document.getElementsByClassName("transactions")[0];
this.showUpdatesButton=document.getElementsByClassName("showUpdates")[0];this.addClickEvents();this.getGroupAndPopulatePage();this.startWorker()};a.prototype.getGroupAndPopulatePage=function(){var b=this;this.storage.getGroup(this.pageContext.getCurrentGroupId()).then(function(a){b.CheckGroupAndPopulatePage(a)})};a.prototype.CheckGroupAndPopulatePage=function(b){var a=this;b?(this.PopulatePage(b),this.synchroniser.getUpdatesForGroup(b.externalId)):this.apiService.getGroupPromise(this.pageContext.getCurrentGroupId()).then(function(b){a.processGroupFromApi(b)})};
a.prototype.processGroupFromApi=function(b){var a=this;this.synchroniser.UpdateGroup(b).then(function(){a.storage.getGroup(a.pageContext.getCurrentGroupId()).then(function(b){a.PopulatePage(b)})})};a.prototype.PopulatePage=function(b){var a=this;b&&(this.group=b,b=[],b.push(this.storage.getPeopleForGroup(this.group.externalId).then(function(b){a.people=b})),b.push(this.storage.getTransactions(this.group.externalId).then(function(b){a.transactions=b})),Promise.all(b).then(function(){a.renderTransactionsAndTotals()}))};
a.prototype.addClickEvents=function(){document.getElementsByClassName("addTransactionButton")[0].addEventListener("click",this.redirectToTransaction.bind(this));document.getElementsByClassName("addPersonButton")[0].addEventListener("click",this.redirectToPeople.bind(this));document.getElementsByClassName("addSectionExpand")[0].addEventListener("click",this.processAddSectionClick.bind(this));this.opaqueLayer.addEventListener("click",this.opaqueLayerClick.bind(this));this.showUpdatesButton.addEventListener("click",
this.refreshPage.bind(this));this.observer.subscribe("deleteTransaction",this.updateTotalsAndSync,this)};a.prototype.refreshPage=function(){var b=this;this.showUpdatesButton.className="showUpdates closed";this.storage.getGroup(this.pageContext.getCurrentGroupId()).then(function(a){b.PopulatePage(a)})};a.prototype.processAddSectionClick=function(){this.addSection.className="addSection active";this.opaqueLayer.className="opaqueLayer"};a.prototype.opaqueLayerClick=function(){this.addSection.className=
"addSection";this.opaqueLayer.className="opaqueLayer visuallyHidden"};a.prototype.startWorker=function(){this.synchroniser.startServiceWorker();this.synchroniser.isServiceWorkerAvailable()&&navigator.serviceWorker.addEventListener("message",this.handleServiceWorkerMessage.bind(this))};a.prototype.handleServiceWorkerMessage=function(b){"reload"==b.data.action&&setTimeout(this.displayShowUpdatesButton.bind(this),1E3)};a.prototype.displayShowUpdatesButton=function(){this.showUpdatesButton.className=
"showUpdates"};a.prototype.renderTransactionsAndTotals=function(){this.populateTotals();this.transactionContainer.innerHTML="";for(var b=0;b<this.transactions.length;b++)new spreaders.view.transaction(this.transactions[b],this.people,this.transactionContainer,this.storage,this.pageContext,this.urlService,this.observer)};a.prototype.refreshPeopleAndPopulateTotals=function(){var b=this;this.storage.getPeopleForGroup(this.group).then(function(a){b.refreshPeopleAndPopulateTotalsCallback(a)})};a.prototype.refreshPeopleAndPopulateTotalsCallback=
function(b){this.people=b;this.populateTotals()};a.prototype.updateTotalsAndSync=function(){var b=this;this.synchroniser.syncWithServer();this.storage.getTransactions(this.currentGroupId).then(function(a){b.updateTotalsCallback(a)})};a.prototype.updateTotalsCallback=function(b){this.transactions=b;this.populateTotals()};a.prototype.populateTotals=function(){this.personTotalsContainer.innerHTML="";var b=this.calculateTotals();b=this.sortPersonTotals(b);for(var a=0;a<b.length;a++)this.createPersonTotal(b[a])};
a.prototype.sortPersonTotals=function(a){a.sort(function(a,b){return b.total-a.total});return a};a.prototype.calculateTotals=function(){for(var a=[],c=0;c<this.people.length;c++){for(var d=new spreaders.model.personTotal(this.people[c]),e=0;e<this.transactions.length;e++){var f=this.transactions[e];f.payer==d.person.externalId&&(d.total+=Number(f.amount));1==f.payees.includes(d.person.externalId)&&(d.total-=Number(f.amount/f.payees.length))}1==this.people[c].isDeleted&&0==d.total||a.push(d)}return a};
a.prototype.createPersonTotal=function(a){var b=document.createElement("li"),d=document.createElement("div");d.className="personName";d.innerHTML=a.person.name;b.appendChild(d);amountClass="";0>a.total&&(amountClass=" negative");d=document.createElement("span");d.className="amount"+amountClass;d.innerHTML="\u00a3"+spreaders.maths.roundAndFormatForCurrency(a.total);a=document.createElement("div");a.className="amount";a.appendChild(d);b.appendChild(a);this.personTotalsContainer.appendChild(b)};a.prototype.redirectToTransaction=
function(){window.location.href=this.urlService.getTransactionPage(this.pageContext.getCurrentGroupId())};a.prototype.redirectToPeople=function(){window.location.href=this.urlService.getPeoplePage(this.pageContext.getCurrentGroupId())};return a}();var storage=new spreaders.storage;
storage.connect().then(function(a){a=new spreaders.urlService;var b=new spreaders.pageContext(a),c=new spreaders.observer,d=new spreaders.apiService,e=new spreaders.sync.synchroniser(storage,d);new spreaders.pages.transactions(b,a,d,storage,c,e)});
