var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,c,e){if(b){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in c||(c[d]={});c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(b){return b instanceof d?b:new d(function(a,c){a(b)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(b){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(b);return this};b.prototype.asyncExecuteBatch_=function(){var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})};var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(b){e(b,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=this.batch_;this.batch_=[];for(var a=0;a<b.length;++a){var c=b[a];delete b[a];try{c()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var d=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{b(a.resolve,a.reject)}catch(h){a.reject(h)}};d.prototype.createResolveAndReject_=
function(){function b(b){return function(g){c||(c=!0,b.call(a,g))}}var a=this,c=!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};d.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof d)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};d.prototype.resolveToNonPromiseObj_=function(b){var a=
void 0;try{a=b.then}catch(h){this.reject_(h);return}"function"==typeof a?this.settleSameAsThenable_(a,b):this.fulfill_(b)};d.prototype.reject_=function(b){this.settle_(2,b)};d.prototype.fulfill_=function(b){this.settle_(1,b)};d.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a|"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=
this.onSettledCallbacks_,a=0;a<b.length;++a)b[a].call(),b[a]=null;this.onSettledCallbacks_=null}};var f=new b;d.prototype.settleSameAsPromise_=function(b){var a=this.createResolveAndReject_();b.callWhenSettled_(a.resolve,a.reject)};d.prototype.settleSameAsThenable_=function(b,a){var c=this.createResolveAndReject_();try{b.call(a,c.resolve,c.reject)}catch(k){c.reject(k)}};d.prototype.then=function(b,a){function c(b,a){return"function"==typeof b?function(a){try{e(b(a))}catch(l){g(l)}}:a}var e,g,f=new d(function(b,
a){e=b;g=a});this.callWhenSettled_(c(b,e),c(a,g));return f};d.prototype.catch=function(b){return this.then(void 0,b)};d.prototype.callWhenSettled_=function(b,a){function c(){switch(e.state_){case 1:b(e.result_);break;case 2:a(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(function(){f.asyncExecute(c)})};d.resolve=c;d.reject=function(b){return new d(function(a,c){c(b)})};d.race=function(b){return new d(function(a,
e){for(var d=$jscomp.makeIterator(b),f=d.next();!f.done;f=d.next())c(f.value).callWhenSettled_(a,e)})};d.all=function(b){var a=$jscomp.makeIterator(b),e=a.next();return e.done?c([]):new d(function(b,d){function f(a){return function(c){g[a]=c;h--;0==h&&b(g)}}var g=[],h=0;do g.push(void 0),h++,c(e.value).callWhenSettled_(f(g.length-1),d),e=a.next();while(!e.done)})};return d},"es6","es3");
$jscomp.polyfill("Object.is",function(a){return a?a:function(b,a){return b===a?0!==b||1/b===1/a:b!==b&&a!==a}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(b,a){var c=this;c instanceof String&&(c=String(c));var d=c.length;for(a=a||0;a<d;a++)if(c[a]==b||Object.is(c[a],b))return!0;return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(b,a){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,a||0)}},"es6","es3");
spreaders.pages.transactions=function(){var a=function(b,a,e,d,f,g){this.group;this.pageContext=b;this.urlService=a;this.apiService=e;this.storage=d;this.observer=f;this.synchroniser=g;this.people=[];this.transactions=[];this.addSection=document.getElementsByClassName("addSection")[0];this.opaqueLayer=document.getElementsByClassName("opaqueLayer")[0];this.personTotalsContainer=document.getElementsByClassName("personTotals")[0];this.transactionContainer=document.getElementsByClassName("transactions")[0];
this.showUpdatesButton=document.getElementsByClassName("showUpdates")[0];this.addClickEvents();this.getGroupAndPopulatePage();this.startWorker()};a.prototype.getGroupAndPopulatePage=function(){var b=this;this.storage.getGroup(this.pageContext.getCurrentGroupId()).then(function(a){b.CheckGroupAndPopulatePage(a)})};a.prototype.CheckGroupAndPopulatePage=function(b){var a=this;b?(this.PopulatePage(b),this.synchroniser.getUpdatesForGroup(b.externalId)):this.apiService.getGroupPromise(this.pageContext.getCurrentGroupId()).then(function(b){a.processGroupFromApi(b)})};
a.prototype.processGroupFromApi=function(b){var a=this;this.synchroniser.UpdateGroup(b).then(function(){a.storage.getGroup(a.pageContext.getCurrentGroupId()).then(function(b){a.PopulatePage(b)})})};a.prototype.PopulatePage=function(a){var b=this;a&&(this.group=a,a=[],a.push(this.storage.getPeopleForGroup(this.group.externalId).then(function(a){b.people=a})),a.push(this.storage.getTransactions(this.group.externalId).then(function(a){b.transactions=a})),Promise.all(a).then(function(){b.renderTransactionsAndTotals()}))};
a.prototype.addClickEvents=function(){document.getElementsByClassName("addTransactionButton")[0].addEventListener("click",this.redirectToTransaction.bind(this));document.getElementsByClassName("addPersonButton")[0].addEventListener("click",this.redirectToPeople.bind(this));document.getElementsByClassName("addSectionExpand")[0].addEventListener("click",this.processAddSectionClick.bind(this));this.opaqueLayer.addEventListener("click",this.opaqueLayerClick.bind(this));this.showUpdatesButton.addEventListener("click",
this.refreshPage.bind(this));this.observer.subscribe("deleteTransaction",this.updateTotalsAndSync,this)};a.prototype.refreshPage=function(){var a=this;this.showUpdatesButton.className="showUpdates closed";this.storage.getGroup(this.pageContext.getCurrentGroupId()).then(function(b){a.PopulatePage(b)})};a.prototype.processAddSectionClick=function(){this.addSection.className="addSection active";this.opaqueLayer.className="opaqueLayer"};a.prototype.opaqueLayerClick=function(){this.addSection.className=
"addSection";this.opaqueLayer.className="opaqueLayer visuallyHidden"};a.prototype.startWorker=function(){this.synchroniser.startServiceWorker();this.synchroniser.isServiceWorkerAvailable()&&navigator.serviceWorker.addEventListener("message",this.handleServiceWorkerMessage.bind(this))};a.prototype.handleServiceWorkerMessage=function(a){"reload"==a.data.action&&setTimeout(this.displayShowUpdatesButton.bind(this),1E3)};a.prototype.displayShowUpdatesButton=function(){this.showUpdatesButton.className=
"showUpdates"};a.prototype.renderTransactionsAndTotals=function(){this.populateTotals();this.transactionContainer.innerHTML="";for(var a=0;a<this.transactions.length;a++)new spreaders.view.transaction(this.transactions[a],this.people,this.transactionContainer,this.storage,this.pageContext,this.urlService,this.observer)};a.prototype.refreshPeopleAndPopulateTotals=function(){var a=this;this.storage.getPeopleForGroup(this.group).then(function(b){a.refreshPeopleAndPopulateTotalsCallback(b)})};a.prototype.refreshPeopleAndPopulateTotalsCallback=
function(a){this.people=a;this.populateTotals()};a.prototype.updateTotalsAndSync=function(){var a=this;this.synchroniser.syncWithServer();this.storage.getTransactions(this.currentGroupId).then(function(b){a.updateTotalsCallback(b)})};a.prototype.updateTotalsCallback=function(a){this.transactions=a;this.populateTotals()};a.prototype.populateTotals=function(){this.personTotalsContainer.innerHTML="";for(var a=this.calculateTotals(),c=0;c<a.length;c++)this.createPersonTotal(a[c])};a.prototype.calculateTotals=
function(){for(var a=[],c=0;c<this.people.length;c++){for(var e=new spreaders.model.personTotal(this.people[c]),d=0;d<this.transactions.length;d++){var f=this.transactions[d];if(f.payer==e.person.id||f.payer==e.person.externalId)e.total-=f.amount;if(1==f.payees.includes(e.person.id)||1==f.payees.includes(e.person.externalId))e.total+=f.amount/f.payees.length}a.push(e)}return a};a.prototype.createPersonTotal=function(a){var b=document.createElement("li");b.innerHTML=a.person.name+": "+a.total;this.personTotalsContainer.appendChild(b)};
a.prototype.redirectToTransaction=function(){window.location.href=this.urlService.getTransactionPage(this.pageContext.getCurrentGroupId())};a.prototype.redirectToPeople=function(){window.location.href=this.urlService.getPeoplePage(this.pageContext.getCurrentGroupId())};return a}();var storage=new spreaders.storage;
storage.connect().then(function(a){a=new spreaders.urlService;var b=new spreaders.pageContext(a),c=new spreaders.observer,e=new spreaders.apiService,d=new spreaders.sync.synchroniser(storage,e);new spreaders.pages.transactions(b,a,e,storage,c,d)});
